### ISSUE TITLE
PLOTCH - fix following issues from end-to-end test with uengage

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/Pre-production#117]
1. /init - the payment struct will come in only after negotiation is enabled. Also, the values are contradictory - type of post-fulfillment (is only for CoD) and so collected_by can't be BAP;
2. the fulfillment id provided by seller in /on_select should be persisted in forward API calls such as /init, etc. Value of "1" is a static value which only shows in on_search to indicate type of delivery. In /confirm, you're creating a completely new fulfillment id. Pls note that fulfillment id should be created by the seller app and persisted from /on_select onwards;
3. /search - finder fee amount is string; also, in /confirm, return window & withholding amount are string;
4. return window and withholding amount should be string in /init, /confirm;
5. why are you updating the timestamp for billing created_at and updated_at in /confirm?
6. /support - ref_id should be transaction_id not order.id

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by BLR-0118** [comment]
@vikramacharya - are all the above fixed? I don't think 1 is fixed yet. For the current MVP, you need to have payment in /confirm with type="ON-ORDER" and collected by "BAP" (for pre-paid payment). For COD payment, type="POST-FULFILLMENT" and collected by "BPP"

**Comment by BLR-0118** [comment]
1. pls check [this](https://github.com/ONDC-Official/Pre-production/blob/main/logs/uengage/plotch-logs/select.json). Why is area_code null?

**Comment by BLR-0118** [comment]
2. also check [this](https://github.com/ONDC-Official/Pre-production/blob/main/logs/uengage/plotch-logs/confirm.json). items should have fulfillment_id for item_id;

**Comment by vikramacharya** [comment]
These issues are fixed. @BLR-0118

**Comment by BLR-0118** [comment]
1. I still see the payment block 
     "payment": {
        "type": "POST-FULFILLMENT",
        "status": "NOT-PAID",
        "collected_by": "BPP",
        "@ondc/org/collected_by_status": "Assert"
      },
in /init. This is the same as issue 1 reported earlier. If BPP asserts the right to collect, it should be in /on_init;
2. Also, the end buyer name should be in fulfillment.end.contact.person.name instead of fulfillment.customer.person.name

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 : these changes were completed yesterday.
